### ISSUE TITLE
cannot download train.zip from google drive

### ISSUE THREAD

**Issue by clockw** [nilc-nlp/CORAA#1]
I cannot download the entire "train.zip" through the google drive link. I have tried different google accounts/devices and some other methods like clearing browsing data and cookies, but it always shows "Request to doc-0k-8s-docs.googleusercontent.com was denied" after about 1/3 of downloading. This problem does not appear in other smaller files.
Did you ever meet this problem before? 

Thanks a lot!

**Comment by arnaldocan** [comment]
This problem seems to be related with restrictions in maximum Google Drive bandwidth usage. 

We are preparing a sliced version of train.zip that should be available in a week or two.

Mean time, could you please try to download the zip once again?

**Comment by Edresson** [comment]
Hi @clockw, 

We temporally hosted the dataset in one of your internal servers to avoid the limit issue. The links are available at: https://github.com/nilc-nlp/CORAA#downloads-

Please let us know if you get any problems during the download using the new links. 

Best,
Edresson

**Comment by clockw** [comment]
Hi @Edresson 
I have tried it and downloaded it successfully. Thank you so much!
